using Test
using HeatStress
using Dates: Date, DateTime
using TimeZones: TimeZone, ZonedDateTime

@testset "solar geometry" begin
    @testset "NREL SPA independent zenith fixtures" begin
        # Generated by pvlib 0.15.2's NREL SPA implementation with altitude 0 m
        # and pressure 0 Pa (geometric, unrefracted zenith); see research.md.
        fixtures = [
            # Equinox, east- and west-positive longitudes, morning/afternoon.
            (DateTime(2024, 3, 20, 6), 77.5946, 12.9716, 19.147918790),
            (DateTime(2024, 3, 20, 18), -122.4194, 37.7749, 48.995453294),
            # Solstices, northern and southern high latitudes.
            (DateTime(2024, 6, 21), 151.2093, -33.8688, 63.703966103),
            (DateTime(2024, 6, 21, 18), -21.9426, 64.1466, 59.297467755),
            (DateTime(2024, 12, 21, 12), -68.3030, -54.8019, 58.387150165),
            (DateTime(2024, 12, 21, 18), -74.0060, 40.7128, 65.939036083),
            # Leap and common-year February/March phase checks.
            (DateTime(2024, 2, 28, 12), 0.0, 0.0, 8.640472030),
            (DateTime(2024, 2, 29, 12), 0.0, 0.0, 8.271657146),
            (DateTime(2024, 3, 1, 12), 0.0, 0.0, 7.901472412),
            (DateTime(2023, 2, 28, 12), 0.0, 0.0, 8.551524062),
            (DateTime(2023, 3, 1, 12), 0.0, 0.0, 8.182292524),
            # Geometric horizon crossings, below and above 90 degrees.
            (DateTime(2024, 3, 20, 6), 0.0, 0.0, 91.848178282),
            (DateTime(2024, 3, 20, 6, 5), 0.0, 0.0, 90.597922272),
            (DateTime(2024, 9, 22, 6), 0.0, 0.0, 88.155898267),
            (DateTime(2024, 9, 22, 18), 0.0, 0.0, 91.893040070),
        ]
        errors = [
            abs(HeatStress.solar_zenith(time, longitude, latitude) - expected_zenith)
            for (time, longitude, latitude, expected_zenith) in fixtures
        ]
        @test maximum(errors) <= 2.0
    end

    @testset "equation-of-time corrected constant" begin
        # Spencer's corrected constant is 0.0000075, not 0.000075.
        @test HeatStress._spencer_equation_of_time(0.0) ≈ -0.0127395 atol = eps(Float64)
    end

    @testset "calendar, horizon, and coordinate boundaries" begin
        @test isfinite(HeatStress.solar_zenith(DateTime(2024, 2, 29, 12), 0.0, 0.0))
        @test isfinite(HeatStress.solar_zenith(DateTime(2023, 3, 1, 12), 0.0, 0.0))
        @test HeatStress.solar_zenith(DateTime(2024, 6, 21), 0.0, 0.0) > 90.0
        @test HeatStress.solar_zenith(DateTime(2024, 6, 21, 12), 180.0, 0.0) ≈
              HeatStress.solar_zenith(DateTime(2024, 6, 21, 12), -180.0, 0.0)
        @test HeatStress.solar_zenith(DateTime(2024, 12, 21, 12), 0.0, 75.0) > 90.0
        @test_throws ArgumentError HeatStress.solar_zenith(DateTime(2024, 6, 21, 12), 181.0, 0.0)
        @test_throws ArgumentError HeatStress.solar_zenith(DateTime(2024, 6, 21, 12), 0.0, -91.0)
        @test_throws MethodError HeatStress.solar_zenith(Date(2024, 6, 21), 0.0, 0.0)
    end

    @testset "equivalent instants" begin
        utc = ZonedDateTime(DateTime(2024, 6, 21, 12), TimeZone("UTC"))
        new_york = ZonedDateTime(DateTime(2024, 6, 21, 8), TimeZone("America/New_York"))
        tokyo = ZonedDateTime(DateTime(2024, 6, 21, 21), TimeZone("Asia/Tokyo"))
        @test HeatStress.solar_zenith(utc, -74.0, 40.7) ≈ HeatStress.solar_zenith(new_york, -74.0, 40.7)
        @test HeatStress.solar_zenith(utc, -74.0, 40.7) ≈ HeatStress.solar_zenith(tokyo, -74.0, 40.7)
    end

    @testset "batch equals scalar and preserves order" begin
        times = [
            DateTime(2024, 6, 21, 12),
            DateTime(2024, 3, 20, 12),
            DateTime(2024, 6, 21, 12),
            DateTime(2024, 12, 21, 12),
        ]
        longitude = [0.0, 0.0, 10.0, 0.0]
        latitude = [45.0, 0.0, 45.0, 75.0]
        expected = HeatStress.solar_zenith.(times, longitude, latitude)
        @test HeatStress.solar_zenith_batch(times, longitude, latitude) ≈ expected
        @test HeatStress.solar_zenith_batch(times, 0.0, 45.0) ≈ HeatStress.solar_zenith.(times, 0.0, 45.0)
        @test HeatStress.solar_zenith_batch(DateTime[], 0.0, 45.0) == Float64[]
        @test_throws ArgumentError HeatStress.solar_zenith_batch(times, longitude[1:3], latitude)
    end

    @testset "numeric promotion" begin
        @test HeatStress.solar_zenith(DateTime(2024, 6, 21, 12), Float32(0), Float32(45)) isa Float64
    end
end
