name: CompatHelper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  compathelper:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/CompatHelper.jl@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
